"""Mouse backend protocol."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class MouseBackend(Protocol):
    """Interface all mouse backends must satisfy."""

    name: str

    def move_to(self, x: int, y: int) -> None: ...
    def mouse_down(self) -> None: ...
    def mouse_up(self) -> None: ...
    def click(self) -> None: ...
    def right_click(self) -> None: ...
    def scroll(self, amount: int) -> None: ...
    def close(self) -> None: ...
